name: OCI SRE Lab Provision

on:
  workflow_dispatch:

jobs:
  terraform-deploy:
    name: Terraform Deploy OCI Lab
    runs-on: ubuntu-latest

    env:
      # These should be stored as GitHub Secrets
      OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
      OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
      OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
      OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}       # Base64 encoded
      OCI_REGION: ${{ secrets.OCI_REGION }}
      COMPARTMENT_OCID: ${{ secrets.COMPARTMENT_OCID }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Install OCI CLI
        run: |
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults --install-dir /home/runner/bin
          echo "/home/runner/bin" >> $GITHUB_PATH
          /home/runner/bin/oci --version

      - name: Configure OCI CLI
        run: |
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/oci_api_key.pem
          chmod 600 ~/oci_api_key.pem
          mkdir -p ~/.oci
          cat > ~/.oci/config <<EOF
          [DEFAULT]
          user=${{ secrets.OCI_USER_OCID }}
          fingerprint=${{ secrets.OCI_FINGERPRINT }}
          key_file=~/oci_api_key.pem
          tenancy=${{ secrets.OCI_TENANCY_OCID }}
          region=${{ secrets.OCI_REGION }}
          EOF
      
          /home/runner/bin/oci iam compartment list --all

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform init -input=false
          terraform plan -input=false \
            -var "tenancy_ocid=$OCI_TENANCY_OCID" \
            -var "user_ocid=$OCI_USER_OCID" \
            -var "fingerprint=$OCI_FINGERPRINT" \
            -var "private_key_path=~/oci_api_key.pem" \
            -var "region=$OCI_REGION" \
            -var "compartment_ocid=$COMPARTMENT_OCID"
      
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -input=false \
            -var "tenancy_ocid=$OCI_TENANCY_OCID" \
            -var "user_ocid=$OCI_USER_OCID" \
            -var "fingerprint=$OCI_FINGERPRINT" \
            -var "private_key_path=~/oci_api_key.pem" \
            -var "region=$OCI_REGION" \
            -var "compartment_ocid=$COMPARTMENT_OCID"

      - name: Test OCI Auth
        run: oci iam compartment list --debug

      - name: Run OCI Python Script
        run: |
          pip install oci
          python scripts/list_instances.py
